### ISSUE TITLE
422 Unprocessable Entity due to SafeMode

### ISSUE THREAD

**Issue by frbar** [markjamesm/MistralSharp#8]
`MistralSharp` is facing the same issue, as depicted here: https://discord.com/channels/1144547040454508606/1184444810279522374/1195108690353717369

Pull-request https://github.com/markjamesm/MistralSharp/pull/7 fixes it.

**Comment by markjamesm** [comment]
Thank you for this! I've merged the changes and have released a fix in the latest version

https://www.nuget.org/packages/MistralSharp/1.0.3
